@startuml
[*] --> UNPAID : CREATE
PAID --> DELIVERED : DELIVER
PAID --> REFUNDED : REFUND
DELIVERED --> FINISHED : FINISH
DELIVERED --> DELIVERED : DELIVER
UNPAID --> CANCELED : CANCEL
UNPAID --> PAID : PAY
CANCELED --> [*]
REFUNDED --> [*]
FINISHED --> [*]
@enduml